---
title: "R code for Assignment 1. Akira Wang."
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 4.a)
```{r 4a}
(mu = matrix(c(3,0,-2),3,1))
(V = matrix(c(2,0,0,0,2,0,0,0,1),3,3))
(A = 1/10 * matrix(c(4,-2,0,-2,1,0,0,0,10),3,3))
A%*%mu
A%*%V%*%t(A)
```

### Question 4.c)
```{r 4c}
M = A%*%V
M%*%M
M
```

### Question 5.b)
```{r 5b}
(X = matrix(c(rep(1,14),13.1,15.3,25.8,1.8,4.9,55.4,39.3,26.7,47.5,6.6,94.7,61.1,135.6,47.6),14,2))
(y = c(27.3,42.4,38.7,4.5,23.0,166.3,109.7,80.1,150.7,20.3,189.7,131.3,404.2,149.0))
(b = solve(t(X)%*%X,t(X)%*%y))
```

### Question 5.c)
```{r 5c}
(e = y - X%*%b)
(SSRes = sum(e^2))
(s2 = SSRes/(14 - (1 + 1)))
```

### Question 5.d)
```{r 5d}
(c(1,18))%*%b
```

### Question 5.e)
```{r 5e}
(inverse = solve(t(X)%*%X))
(H = X %*% inverse %*% t(X))
i = 13 # index of scallop is 13
(standardised_residuals = e[i]/sqrt(s2*(1 - H[i,i])))
```

### Question 5.f)
```{r 5f}
(D = (standardised_residuals^2/(1 + 1))*(H[i,i]/(1 - H[i,i])))
```


